[package]
name = "mushroom"
authors = ["Dennis Sprokholt <me@dennis.life>"]
description = "mushroom"
readme = "README.md"
license = "MIT"
repository = "https://github.com/sourcedennis/mushroom"
edition = "2021"
version = "0.0.0"

[dependencies]
